### ISSUE TITLE
error when yts-downloader 'aquamen'

### ISSUE THREAD

**Issue by seifeslimene** [FlashBlaze/yts-downloader#3]
When I did run this command :
`yts-downloader 'aquaman'`
I got this error :
```
Traceback (most recent call last):
  File "/home/seifeslimene/.local/bin/yts-downloader", line 8, in <module>
    sys.exit(main())
  File "/home/seifeslimene/.local/lib/python3.8/site-packages/yts_downloader/yts_downloader.py", line 23, in main
    movie_count = int((str(h2)[5:11].replace(',', '')))
ValueError: invalid literal for int() with base 10: '<b>34'
```
What's wrong?

**Comment by flashblaze** [comment]
@SeifESlimene thanks for reporting. Haven't looked into Python and this CLI in a while. Found glaring issues while taking a look. I'll fix this and let you know.
